### ISSUE TITLE
Docker Compose with 2 Plugins

### ISSUE THREAD

**Issue by kvogel456** [tillsteinbach/CarConnectivity-connector-seatcupra#9]
Hi there!

Loving the Project, pls keep the good work!!

I'm struggling with getting my docker container get work with more than 1 connector.

If i try starting the container docker compose with connector "seatcupra" and 1 plugin "mqtt", everything is working fine.

But when trying starting same container with connector "seatcupra" and plugins "mqtt" + "webui", i get errors:

`carconnectivity-mqtt-1  | 2025-03-02T10:03:02+0000:carconnectivity-mqtt:CRITICAL:carconnectivity_base:There was a problem with the configuration: Invalid configuration: connector type 'seatcupra' is not known
carconnectivity-mqtt-1  | There was a problem with the configuration`

here's my docker-compose-yml:

```
services:
  carconnectivity-mqtt:
    image: "tillsteinbach/carconnectivity-mqtt:edge"
    environment:
      - ADDITIONAL_INSTALLS=carconnectivity-connector-seatcupra
      - ADDITIONAL_INSTALLS=carconnectivity-plugin-webui
    volumes:
      - /var/lib/docker/apps/carconnectivity-mqtt/carconnectivity.json:/carconnectivity.json
```

and carconnectivity.json:

```
{
    "carConnectivity": {
        "log_level": "error", 
        "connectors": [
            {
                "type": "seatcupra", 
                "config": {
                    "interval": 600, 
                    "username": "user", 
                    "password": "pass" 
                }
            }
        ],
        "plugins": [
            {
                "type": "mqtt", 
                "config": {
                    "broker": "10.10.10.10", 
                    "username": "user", 
                    "password": "pass" 
                }
            },
            {
                "type": "webui",
                "disabled": false,
                "config": {
                    "log_level": "error",
                    "username": "admin",
                    "password": "secret"
                }
            }
        ]
    }
}
```

what im doing wrong?

thanks in advantage for help guys!
